# Generated by Django 5.1 on 2024-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
    ]
